### ISSUE TITLE
dnscontrol-action v 3.31.4 outputs out-of-date warning about using -diff2

### ISSUE THREAD

**Issue by apotek** [koenrh/dnscontrol-action#117]
I am running dnscontrol-preview with v 3.31.4:

```
      - name: DNSControl preview
        uses: koenrh/dnscontrol-action@v3.31.4
        id: dnscontrol_preview
```

Running this, I get the following output:

"[INFO: Old diff algorithm in use. Please test `dnscontrol --diff2 preview` (or push) as it will be the default in releases after 2023-05-07."

diff2 has already been released to the DNSControl and has been a part of DNSControl by default (without specifying diff2) since May 2023. 

In fact, when I run DNSControl (locally) with --diff2, I get this warning instead:

" [WARNING: Please remove obsolete --diff2 flag. This will be an error in v5 or later. See https://github.com/StackExchange/dnscontrol/issues/2262]"

I am using DNSControl 4.11

Should dnscontrol-action be updated to a more recent version?

**Comment by apotek** [comment]
Looks like [this action](https://github.com/marketplace/actions/dnscontrol-action-icme) is on 4.11.0. I'll see if it works.

**Comment by emmahsax** [comment]
@apotek was switching to that other linked Action a seamless change? Did it correctly resolve the warnings?

**Comment by pythoninthegrass** [comment]
Got bit by this today. Ended up just rolling a simpler `ubuntu-latest` setup:

```yaml
      - name: Install DNSControl
        run: |
          ARCH="$(dpkg --print-architecture)"
          curl -sSLO "https://github.com/StackExchange/dnscontrol/releases/download/v${DNSCONTROL_VERSION}/dnscontrol-${DNSCONTROL_VERSION}.${ARCH}.deb"
          sudo dpkg -i "dnscontrol-${DNSCONTROL_VERSION}.${ARCH}.deb"

     - name: Create creds.json
        run: |
          cat > creds.json << EOF
          ...

      - name: DNSControl check
        run: dnscontrol check --config dnsconfig.js
```

Appreciate all the dozens of runs this repo seamlessly abstracted! 🙏
