### ISSUE TITLE
Document how to get this action to publish the  output of the 'preview' command as a PR comment

### ISSUE THREAD

**Issue by koenrh** [koenrh/dnscontrol-action#28]
See: https://github.com/koenrh/dnscontrol-action/pull/26

> My specific usecase was that I want my own GitHub action to comment the diff of `dnscontrol preview` on the PR, instead of having to dig down into the "Checks" tab after every push. I'm open to other names than "output", but I wanted to keep it nice and generic, as "diff" wouldn't be suitable for commands like `dnscontrol push` or `check`.

Something along the lines of:

```yaml
- name: Comment diff on PR
  uses: unsplash/comment-on-pr@master
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  with:
    msg: |
      ```
      ${{ steps.preview.outputs.output }}
      ```
    check_for_duplicate_msg: true
```
